create_user() {
    getent passwd monero &>/dev/null || {
        echo -n ">>> Creating monero user... "
        useradd --system --user-group -m --home /var/lib/monero monero
        echo "done"
    } # NOTE: we do not autoremove user due to security concerns (Arch policy)
    mkdir -p /var/log/monero && chown monero:monero /var/log/monero
}

post_install() {
    create_user
}

post_upgrade() {
  create_user
}
